### ISSUE TITLE
Support for HT-A7000 (Power state)

### ISSUE THREAD

**Issue by steplein** [kovalev-sergey/homebridge-sony-audio#10]
Dear team, first let me thank you for this great plug-in and your efforts! I am using the new Sony HT-A7000 (which is not officially supported). The device gets recognised and also the current broadcast is propagated to home. What I am missing is the on/off state (and switch). Any ideas what it takes get this done? Thanks in advance and best regards.

**Comment by kovalev-sergey** [comment]
Hi,  thanks for the kind words.

Everything should work out of the box.

Can you explain in more detail what the difficulties arise? 
Ideally with screenshots

**Comment by steplein** [comment]
﻿
Hey Sergey,

thanks for your fast reaction.

Let me give you some context first:
1. I am using as bridge to Homekit a Raspberry PI with hoobs (latest version)
2. All relevant devices are in the same network.
3. As Homekit central an AppleTV 4K and iPad Pro is in use.

The screenshot below shows a situation where AppleTV is stream from Tidal through Airplay to the Sony device. I would expect that the Sony device is also white not grey and also show current state (showing to be in use). It never is and consequently I am also not able to switch it on or off.

I also restarted the plug-in to share with you the protocol entries generated.

Hope this gives an idea where the issue maybe. If you need more or if I can help somehow let me know.

Best

Stephan

**Comment by steplein** [comment]
hey sergey, played around a little bit and found out that the „persist“ sub directory under „/var/lib/hoobs/sonyaudiobridge“ doesn’t exist. there is rather a subdirectory „sonyaudiobridge.persist“ under „/var/lib/hoobs“. this is causing the log entry. not sure if this helps resolve the concrete issue described, still maybe worth fixing. thanks in advance and have a good day!

**Comment by kovalev-sergey** [comment]
Hi steplein 
Can you drop full logs here?

Sergey

On 11 Dec 2021, at 15:51, steplein ***@***.***> wrote:

﻿
hey sergey, played around a little bit and found out that the „persist“ sub directory under „/var/lib/hoobs/sonyaudiobridge“ doesn’t exist. there is rather a subdirectory „sonyaudiobridge.persist“ under „/var/lib/hoobs“. this is causing the log entry. not sure if this helps resolve the concrete issue described, still maybe worth fixing. thanks in advance and have a good day!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by steplein** [comment]
sure sergey.

28.11.2021, 15:34:34 Sony Audio Bridge Loaded plugin 'homebridge-sony-audio'
28.11.2021, 15:34:34 Sony Audio Bridge Loading 1 platforms...
28.11.2021, 15:34:34 Sony Audio Bridge Bridge is running on port 55826.
28.11.2021, 15:34:36 Sony Audio Bridge Sony Audio Platform Adding new accessory: HT-A7000
28.11.2021, 15:34:36 Sony Audio Bridge Sony Audio Platform Compatible device found, added: HT-A7000
28.11.2021, 15:34:36 Sony Audio Bridge HT-A7000 38AB is running on port 46149.
**28.11.2021, 15:34:36 Sony Audio Bridge WARNUNG unhandled rejection: Error: ENOENT: no such file or directory, open
"/var/lib/hoobs/sonyaudiobridge/persist/SonyAudioAccessorySettings.28E3FF4CFFCE42A6834CB43E5CC55FAE.json'**

i refer to the warning in the last line.  

/var/lib/hoobs/sonyaudiobridge/persist/ does not exist.

still the file „SonyAudioAccessorySettings.28E3FF4CFFCE42A6834CB43E5CC55FAE.json“ can be found under „/var/lib/hoobs/sonyaudiobridge.persist/„ in my case

best

**Comment by kovalev-sergey** [comment]
yes it is definitely not good

I'll try to figure out the problem. 
But I have no way to replicate a similar platform.  and there is no time for this yet ((
but I remember and will definitely resolve the issue asap )

Sergey

On 11 Dec 2021, at 16:16, steplein ***@***.***> wrote:

﻿
sure sergey.

28.11.2021, 15:34:34 Sony Audio Bridge Loaded plugin 'homebridge-sony-audio'
28.11.2021, 15:34:34 Sony Audio Bridge Loading 1 platforms...
28.11.2021, 15:34:34 Sony Audio Bridge Bridge is running on port 55826.
28.11.2021, 15:34:36 Sony Audio Bridge Sony Audio Platform Adding new accessory: HT-A7000
28.11.2021, 15:34:36 Sony Audio Bridge Sony Audio Platform Compatible device found, added: HT-A7000
28.11.2021, 15:34:36 Sony Audio Bridge HT-A7000 38AB is running on port 46149.
28.11.2021, 15:34:36 Sony Audio Bridge WARNUNG unhandled rejection: Error: ENOENT: no such file or directory, open
"/var/lib/hoobs/sonyaudiobridge/persist/SonyAudioAccessorySettings.28E3FF4CFFCE42A6834CB43E5CC55FAE.json'

i refer to the warning in the last line.

/var/lib/hoobs/sonyaudiobridge/persist/ does not exist.

still the file „SonyAudioAccessorySettings.28E3FF4CFFCE42A6834CB43E5CC55FAE.json“ can be found under „/var/lib/hoobs/sonyaudiobridge.persist/„ in my case

best

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kovalev-sergey** [comment]
Hi @steplein 
I found out that this is a hoobs bug.

Can you check if directory `/var/lib/hoobs/sonyaudiobridge/persist/` exists?
And if it doesn't exist, try to create it. Then check if this error appears again.

**Comment by steplein** [comment]
hey sergey, already did. this and copied the files in. with this the error in the log is gone, still the other issues persist. thanks for investigating.

**Comment by kovalev-sergey** [comment]
I have released the new release (v1.1.1)
Can't claim to help - I still can't reproduce this issue on my side.

Before updating, please do the following (to avoid side effects):
1. Remove your Sony from your home app
2. Delete the files `AccessoryInfo.XXXXXXXXXXXX.json`, `IdentifierCache.XXXXXXXXXXXX.json` related to Sony (you can understand the content) and `SonyAudioAccessorySettings.XXXXXXXXXXXX.json`
3. After that you can update the plugin.

if the issue still persists, you need to run the hoobs in debug mode and send me all the logs related to Sony

**Comment by steplein** [comment]
hey sergey, thanks follow your instruction also clean everything from /var/lib/hoobs. the issue with the wrong pointer to the path is fixed. no error in the log anymore. other issues still persist. thanks again.

**Comment by steplein** [comment]
hey sergey, just installed version 1.2. now everything works light it should. great effort thanks!

**Comment by kovalev-sergey** [comment]
good news
