### ISSUE TITLE
The accessories doesn’t appear

### ISSUE THREAD

**Issue by Reddyzinho** [kovalev-sergey/homebridge-sony-audio#22]
**Describe The Bug:**
The accessories doesn’t appear. Only the button ON/OFF

**To Reproduce:**
After reboot of Homebridge, the accessories doesn’t appear on main screen. Only a big ON/OFF button. The accessories are there, but doesn’t appear on the main page near the button. I have 6 accessories related with my Soundbar HT-Z9

**Expected behavior:**
I should espect a scroll near th button ON/OFF with the accessories 

```json
Show your Homebridge config.json here, remove any sensitive information.

{
            "name": "Sony Soundbar",
            "platform": "SonyAudio"
        },


**Screenshots:**


![E6A48C68-9AA9-494A-A74E-35763ACF437D](https://user-images.githubusercontent.com/3985096/154298224-902bc4ec-d4e6-4191-899a-37bcef1d2b26.png)

![E8289F4B-BB07-4464-91FE-7E9C3398BDED](https://user-images.githubusercontent.com/3985096/154298283-d0d69ec5-42c4-4a55-bb11-1d59c87a28bb.png)


**Environment:**

* **Plugin Version**:
* Latest
 
* **Homebridge Version**: <!-- homebridge -V -->
Latest

* **Node.js Version**: <!-- node -v -->
16.04.0

* **NPM Version**: <!-- npm -v -->
8.3.1

* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
Raspberry Homebridge 



<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by kovalev-sergey** [comment]
Hi,
Try to reload Home app

Sergey

On 16 Feb 2022, at 18:32, Tiago Cunha ***@***.***> wrote:

﻿
Describe The Bug:
The accessories doesn’t appear. Only the button ON/OFF

To Reproduce:
After reboot of Homebridge, the accessories doesn’t appear on main screen. Only a big ON/OFF button. The accessories are there, but doesn’t appear on the main page near the button. I have 6 accessories related with my Soundbar HT-Z9

Expected behavior:
I should espect a scroll near th button ON/OFF with the accessories

Show your Homebridge config.json here, remove any sensitive information.

{
            "name": "Sony Soundbar",
            "platform": "SonyAudio"
        },


**Screenshots:**


![E6A48C68-9AA9-494A-A74E-35763ACF437D](https://user-images.githubusercontent.com/3985096/154298224-902bc4ec-d4e6-4191-899a-37bcef1d2b26.png)

![E8289F4B-BB07-4464-91FE-7E9C3398BDED](https://user-images.githubusercontent.com/3985096/154298283-d0d69ec5-42c4-4a55-bb11-1d59c87a28bb.png)


**Environment:**

* **Plugin Version**:
* Latest
 
* **Homebridge Version**: 
Latest

* **Node.js Version**: 
16.04.0

* **NPM Version**: 
8.3.1

* **Operating System**: 
Raspberry Homebridge

**Comment by Reddyzinho** [comment]
Thanks. It worked

Another problem is that when I restart my homebridge , the Sony soundbar appear again as a favourite in the main screen. I only have it selected in a specific room and not as a favourite. How can I change this ? I put in setting to remove from favourites, but then … restarting the homebridge, appears again ;(( 


Atentamente,

Tiago Cunha

No dia 16/02/2022, às 16:55, Sergey Kovalev ***@***.***> escreveu:

﻿
Hi,
Try to reload Home app

Sergey

On 16 Feb 2022, at 18:32, Tiago Cunha ***@***.***> wrote:

﻿
Describe The Bug:
The accessories doesn’t appear. Only the button ON/OFF

To Reproduce:
After reboot of Homebridge, the accessories doesn’t appear on main screen. Only a big ON/OFF button. The accessories are there, but doesn’t appear on the main page near the button. I have 6 accessories related with my Soundbar HT-Z9

Expected behavior:
I should espect a scroll near th button ON/OFF with the accessories

Show your Homebridge config.json here, remove any sensitive information.

{
"name": "Sony Soundbar",
"platform": "SonyAudio"
},


**Screenshots:**


![E6A48C68-9AA9-494A-A74E-35763ACF437D](https://user-images.githubusercontent.com/3985096/154298224-902bc4ec-d4e6-4191-899a-37bcef1d2b26.png)

![E8289F4B-BB07-4464-91FE-7E9C3398BDED](https://user-images.githubusercontent.com/3985096/154298283-d0d69ec5-42c4-4a55-bb11-1d59c87a28bb.png)


**Environment:**

* **Plugin Version**:
* Latest

* **Homebridge Version**: 
Latest

* **Node.js Version**: 
16.04.0

* **NPM Version**: 
8.3.1

* **Operating System**: 
Raspberry Homebridge 




—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kovalev-sergey** [comment]
This is the specificity of either the Homebridge or the HomeKit. Maybe a bug. 

The plugin does not and cannot manage its location in the home app. 

¯\_(ツ)_/¯

Sergey

On 16 Feb 2022, at 20:13, Tiago Cunha ***@***.***> wrote:

﻿
Thanks. It worked

Another problem is that when I restart my homebridge , the Sony soundbar appear again as a favourite in the main screen. I only have it selected in a specific room and not as a favourite. How can I change this ? I put in setting to remove from favourites, but then … restarting the homebridge, appears again ;(( 


Atentamente,

Tiago Cunha

No dia 16/02/2022, às 16:55, Sergey Kovalev ***@***.***> escreveu:

﻿
Hi,
Try to reload Home app

Sergey

On 16 Feb 2022, at 18:32, Tiago Cunha ***@***.***> wrote:

﻿
Describe The Bug:
The accessories doesn’t appear. Only the button ON/OFF

To Reproduce:
After reboot of Homebridge, the accessories doesn’t appear on main screen. Only a big ON/OFF button. The accessories are there, but doesn’t appear on the main page near the button. I have 6 accessories related with my Soundbar HT-Z9

Expected behavior:
I should espect a scroll near th button ON/OFF with the accessories

Show your Homebridge config.json here, remove any sensitive information.

{
"name": "Sony Soundbar",
"platform": "SonyAudio"
},


**Screenshots:**


![E6A48C68-9AA9-494A-A74E-35763ACF437D](https://user-images.githubusercontent.com/3985096/154298224-902bc4ec-d4e6-4191-899a-37bcef1d2b26.png)

![E8289F4B-BB07-4464-91FE-7E9C3398BDED](https://user-images.githubusercontent.com/3985096/154298283-d0d69ec5-42c4-4a55-bb11-1d59c87a28bb.png)


**Environment:**

* **Plugin Version**:
* Latest

* **Homebridge Version**: 
Latest

* **Node.js Version**: 
16.04.0

* **NPM Version**: 
8.3.1

* **Operating System**: 
Raspberry Homebridge 




—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
