### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by HomeCoops** [kovalev-sergey/homebridge-sony-audio#4]
How do I control audio of a Sony STR-DN1080 Receiver? Power and inputs work fine
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by kovalev-sergey** [comment]
@HomeCoops,
Sorry for the late reply, did not see the notification.
What you mean about audio?

If the question about volume control,
you can use Apple TV controls in Control Center on an iOS or iPadOS device. 

To adjust the volume, press the volume buttons on your iOS or iPadOS device when the Apple TV controls in Control Center are open.

**Comment by bed42** [comment]
I have the same 'issue' with volume control on my Sony soundbar... I think this is because I have my TV volume control set to the audio receiver so the tv / physical apple remote controls the volume). The iOS volume control is either disabled or does nothing. I'll play around some more to confirm when I have a chance.
